### ISSUE TITLE
Add version tags to make it easier to track down the releases

### ISSUE THREAD

**Issue by jxltom** [Frozenball/pytest-sugar#163] opened 2018-11-07 14:33 UTC
It looks like there is no version tags in the repo. The releases in pypi https://pypi.org/project/pytest-sugar/#history is already 0.9.1. 

It will be nice to tag release versions, so the users or developer could checkout different versions easily.

**Comment by Frozenball** [comment] 2018-11-08 21:16
Duplicate of #137

**Closed by Frozenball** 2018-11-08 21:16 UTC
