### ISSUE TITLE
Obfuscated output with LANG=C

### ISSUE THREAD

**Issue by kiilerix** [Frozenball/pytest-sugar#141] opened 2018-08-19 20:27 UTC
When running on Linux as
LANG=C py.test
it will output ansi sequences like literally '\x1b[36m' and unicode as literally '\u2015'.

I would expect it to work as usual, probably emitting ansi codes as usual. pytest-sugar itself should not try to emit its own utf8 characters but should fall back to some pure ascii.

(I wonder how setting LANG can influence that. It kind of would make sense if setting TERM to something incorrect ... but in that case it also should fall back to not emitting ansi codes.)

Using:
pytest==3.7.2
pytest-benchmark==3.1.1
pytest-localserver==0.4.1
pytest-runner==4.2
pytest-sugar==0.9.1

**Comment by blueyed** [comment] 2018-08-29 17:43
Could not reproduce this.

**Comment by Frozenball** [comment] 2018-10-17 19:32
I guess this is a duplicate of #91?

**Closed by Frozenball** 2018-10-17 19:32 UTC
